ls -al is more reliable in more places

diff --git a/shared/dots/bash_profile b/shared/dots/bash_profile
--- a/shared/dots/bash_profile
+++ b/shared/dots/bash_profile
@@ -1,6 +1,6 @@
 os=unknown
 cpu=unknown
-selfpath=$(stat -F ~/.bash_profile | awk '{ print $(NF) }')
+selfpath=$(ls -al ~/.bash_profile | awk '{ print $(NF) }')
 repo=$(cd $(dirname ${selfpath})/../.. && pwd)
 
 if [[ $OSTYPE == "linux-gnu"* ]]; then
@@ -20,7 +20,7 @@ elif [[ $OSTYPE == "darwin"* ]]; then
     cpu=x86
   fi
 else
-  1>&2 echo "Cannot install on this OS: ${OSTYPE}"
+  echo 1>&2 "Cannot install on this OS: ${OSTYPE}"
   exit 2
 fi
 
